<?php

while( $vol == "" ) {
	echo "What volume is this issue in?\n";
	$vol = trim(fgets(STDIN));
}

while( $issue == "" ) {
	echo "What issue is this?\n";
	$issue = trim(fgets(STDIN));
}

include("/home/soxred93/wikibot.classes.php");

$user = 'SoxBot';
$pass = file_get_contents('/home/soxred93/.password');
 
//Setup the classes
$wpapi  = new wikipediaapi;
$wpq    = new wikipediaquery;
$wpi    = new wikipediaindex;
$wpapi->login($user,$pass);

if( $argv[2] != "--nosource" ) {
	$wpi->forcepost(
		'User:'.$user.'/Source/Signpost',
		'The following post was automatically generated by [[User:'.$user.'|'.$user."]].\n\n<pre>" .
		htmlentities(file_get_contents(__FILE__)) . 
		"</pre>",
		'Automatic source code upload ([[WP:BOT|BOT]])'
	);
}
 

$delivery['page']  = 'Wikipedia:Wikipedia_Signpost/Tools/Spamlist';
$delivery['text']  = "\n\n{{subst:Wikipedia:Wikipedia Signpost/Tools/Spamlist/Message}} \n\r<small>Delivered by ~~~ at ~~~~~</small>";
$delivery['sum']   = "Delivering Vol. $vol, Issue $issue of Wikipedia Signpost ([[User:".$user."|BOT]])";


preg_match_all('/[^\>]\[\[(User|User_talk|User talk):.+\]\]/Si',$wpq->getpage($delivery['page']),$pages);
foreach ($pages[0] as $i => $p) {
	$temp = explode('|',$p);
	$p = preg_replace(array('/.*\[\[(User|User_talk|User talk):/Si','/\]\].*/i'),'',$temp[0]);
	deliver($p);
}

function deliver($page) {
	//Delivers the newsletter to $page
	global $wpi, $wpapi, $wpq, $delivery;
	$page = "User_talk:".trim($page);
	$content = $wpq->getpage($page);
	if (preg_match('/#REDIRECT \[\[.+\]\]/Si',$content,$new_page)) {
		$page = str_replace(array('#REDIRECT [[',']]'),'',$new_page[0]);
		if( !preg_match('/\[\[(User|User_talk|User talk):.+\]\]/Si', $page) ) return;
	}
	$content = $wpq->getpage($page);
   	echo "Sending to $page\n";
   	if ($content != ''){
   		$wpi->post($page,$content.$delivery['text'],$delivery['sum'],$minor = false,$rv = null,$bot = false);
   	}
} 
