<?php

while( $episode == "" ) {
	echo "What episode is this?\n";
	$episode = trim(fgets(STDIN));
}

include("/home/soxred93/wikibot.classes.php");

$user = 'SoxBot II';
$pass = file_get_contents('/home/soxred93/.password');
 
//Setup the classes
$wpapi  = new wikipediaapi;
$wpq    = new wikipediaquery;
$wpi    = new wikipediaindex;
$wpapi->login($user,$pass);

if( $argv[2] != "--nosource" ) {
	$wpi->forcepost(
		'User:'.$user.'/Source/Wikivoices',
		'The following post was automatically generated by [[User:'.$user.'|'.$user."]].\n\n<pre>" .
		htmlentities(file_get_contents(__FILE__)) . 
		"</pre>",
		'Automatic source code upload ([[WP:BOT|BOT]])'
	);
}
 

$delivery['page']  = 'Wikipedia:Wikivoices/Subscribe';
$delivery['text']  = "\n\n{{subst:Wikipedia:Wikivoices/Subscribe/Message}} \n\r<small>Delievered by ~~~ at ~~~~~</small>";
$delivery['sum']   = "Delivering episode $episode of Wikivoices ([[User:".$user."|BOT]])";


//preg_match_all('/[^\>]\[\[(User|User_talk|User talk):.+\]\]/Si',$wpq->getpage($delivery['page']),$pages);
preg_match_all('/\{\{user\|(.*?)\}\}/i',$wpq->getpage($delivery['page']),$pages);
print_r($pages[1]);
die();
foreach ($pages[1] as $p) {
	echo "Delivering to $p...\n";
	//deliver($p);
}

function deliver($page) {
	//Delivers the newsletter to $page
	global $wpi, $wpapi, $wpq, $delivery;
	$page = "User_talk:".trim($page);
	$content = $wpq->getpage($page);
	if (preg_match('/#REDIRECT \[\[.+\]\]/Si',$content,$new_page)) {
		$page = str_replace(array('#REDIRECT [[',']]'),'',$new_page[0]);
	}
	$content = $wpq->getpage($page);
   	echo "Sending to $page\n";
   	$wpi->post($page,$content.$delivery['text'],$delivery['sum'],$minor = false,$rv = null,$bot = false);
} 
